# Generated by Django 3.2.10 on 2021-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211211_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='static/products/')),
                ('price', models.IntegerField()),
                ('prod_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
