# Generated by Django 3.2.10 on 2021-12-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sweets', 'sweets'), ('choclates', 'choclates'), ('Junk Food', 'Junk Food')], default='sweets', max_length=10),
        ),
    ]
